[package]
name = "rshi"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.2.1" # Actix Web is a powerful, pragmatic, and extremely fast web framework for Rust